Repository HrBjarup/Fog-Carport, pull requests merged in 2019-05, with the labels that each got.

#43 The changes from technical meeting
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/java/presentation/makeCarportSimple.java
  FogCarport/src/main/webapp/index.jsp
Labels: bug

#48 Fix for getMaterial(int id) in MaterialMapper.
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
Labels: bug

#47 Updated DDL, DML
  extraFiles/Database docs/create(DDL).sql
  extraFiles/Database docs/insertion(DML).sql
Labels: bug

#49 Task#34 - Base algorithm - unfinished
  FogCarport/src/main/java/logic/BaseCalc.java
  FogCarport/src/test/java/logic/BaseCalcTest.java
Labels: enhancement

#51 #32FlatRoof - Merge for weekly release
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/DBConnector.java
  FogCarport/src/main/java/data/exceptions/AlgorithmException.java
  FogCarport/src/main/java/data/models/MaterialModel.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  extraFiles/Database docs/insertion(DML).sql
Labels: enhancement

#50 Alpha advanced roofWithIncline algorithm
  FogCarport/src/main/java/data/models/MaterialModel.java
  FogCarport/src/main/java/logic/PartslistLogic.java
  FogCarport/src/main/java/logic/RoofRaisedCalc.java
  FogCarport/src/test/java/logic/RoofRaisedCalcTest.java
Labels: enhancement

#56 Added Shed SVG drawing.
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
  FogCarport/src/main/webapp/svg/shed.jsp
Labels: enhancement

#57 Able to see all orders and choose a single one and view its details.
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/webapp/allOrders.jsp
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: enhancement

#58 RoofIncline first full edition implemented
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/test/java/FogTestSuite.java
  FogCarport/src/test/java/logic/Calculations/RoofRaisedCalcTest.java
Labels: enhancement

#60 View Employee and Customer attached to an Order.
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/data/models/CustomerModel.java
  FogCarport/src/main/java/data/models/EmployeeModel.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: enhancement

#61 Task#93 shed-.jsp menu
  FogCarport/src/main/java/presentation/makeCarportSimple.java
  FogCarport/src/main/webapp/css/validation.css
  FogCarport/src/main/webapp/footer.jsp
  FogCarport/src/main/webapp/header.jsp
  FogCarport/src/main/webapp/javascript/OrderValidationShed.js
  FogCarport/src/main/webapp/makeCarport.jsp
Labels: enhancement

#62 Task#34 Base algorithm finished
  FogCarport/pom.xml
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
  FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
Labels: enhancement

#65 Added customer info to .jsp.
  FogCarport/src/main/webapp/makeCarport.jsp
Labels: enhancement

#73 Updated materials in ShedLogic to use final fields.
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
Labels: refactoring

#71 View partslist and view SVG buttons.
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement

#76 Fixed Issue #74
  FogCarport/src/main/webapp/homepage.jsp
Labels: bug

#75 Task 32 & 96 | Flat Roof | algorithm & testing
  FogCarport/pom.xml
  FogCarport/src/main/java/data/models/PartslistModel.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/test/java/FogTestSuite.java
  FogCarport/src/test/java/logic/Calculations/RoofFlatCalcTest.java
  extraFiles/Database docs/insertion(DML).sql
Labels: enhancement

#77 Consolidated JSP & CSS
  FogCarport/src/main/webapp/css/footer.css
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/css/index.css
  FogCarport/src/main/webapp/css/validation.css
  FogCarport/src/main/webapp/index.jsp
  FogCarport/src/main/webapp/javascript/Navbar.js
  FogCarport/src/main/webapp/javascript/OrderValidation.js
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/navbar.jsp
Labels: enhancement, refactoring

#81 Fix for Issue#79
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/webapp/WEB-INF/web.xml
  FogCarport/src/main/webapp/index.jsp
Labels: bug, refactoring

#85 SVG drawing jsp and structure
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/makeCarportSimple.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/allOrders.jsp
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
  FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
  FogCarport/src/test/java/logic/Calculations/ShedLogicTest.java
Labels: bug, enhancement, refactoring

#87 Task#106 SVG drawing for carport base
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
  FogCarport/src/main/webapp/testsvg.jsp
  FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
Labels: enhancement

#100 Fixed bug in SVG drawing Base missing posts
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
Labels: bug

#101 Updated Customer with Password in SQL DB.
  extraFiles/Database docs/create(DDL).sql
  extraFiles/Database docs/insertion(DML).sql
Labels: refactoring

#103 phone number database fix
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/presentation/viewSVG.java
  extraFiles/Database docs/create(DDL).sql
  extraFiles/Database docs/insertion(DML).sql
Labels: refactoring

#102 Login Feature.
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/data/models/CustomerModel.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/java/presentation/createUser.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/webapp/createUser.jsp
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/index.jsp
  FogCarport/src/main/webapp/login.jsp
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/navbar.jsp
Labels: bug, enhancement, refactoring

#105 Fixed shed part of Issue#104
  FogCarport/src/main/webapp/javascript/global.js
Labels: bug

#109 Validation
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/link.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/java/presentation/viewSVG.java
Labels: bug

#111 issue#90 - makeCarport has its own command.
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/navbar.jsp
  extraFiles/Database docs/insertion(DML).sql
Labels: enhancement

#113 Task#167 Create user (Customer)
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/createUser.java
  FogCarport/src/main/webapp/createUser.jsp
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/index.jsp
Labels: enhancement

#115 Payment button added to viewOrder.jsp.
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/webapp/viewOrder.jsp
  extraFiles/Diagrams/ER_diagram_V4.PNG
Labels: enhancement

#119 Session use fixed
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: refactoring

#123 Task#148 viewSVG dynamic
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement

#121 navbar: login/logout button added
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/LogOut.java
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/navbar.jsp
Labels: enhancement

#126 Custom Exceptions changed
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/data/exceptions/AlgorithmException.java
  FogCarport/src/main/java/data/exceptions/DataException.java
  FogCarport/src/main/java/data/exceptions/UserException.java
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/PartslistLogic.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/LogOut.java
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/createUser.java
  FogCarport/src/main/java/presentation/link.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
  FogCarport/src/test/java/logic/Calculations/RoofRaisedCalcTest.java
  FogCarport/src/test/java/logic/Calculations/ShedLogicTest.java
Labels: refactoring

#118 Helptext Feature
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/models/PartslistModel.java
  FogCarport/src/main/java/logic/Calculations/BaseCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
  FogCarport/src/test/java/logic/Calculations/RoofFlatCalcTest.java
  FogCarport/src/test/java/logic/Calculations/RoofRaisedCalcTest.java
  FogCarport/src/test/java/logic/Calculations/ShedLogicTest.java
  extraFiles/Database docs/create(DDL).sql
  extraFiles/Database docs/insertion(DML).sql
Labels: enhancement, refactoring

#122 method="POST"
  FogCarport/src/main/webapp/createUser.jsp
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/login.jsp
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: bug

#127 Algorithm updated, accounts for different materials, testing expanded, AlgorithmException added again
  FogCarport/src/main/java/data/exceptions/AlgorithmException.java
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/test/java/logic/Calculations/RoofRaisedCalcTest.java
Labels: enhancement, refactoring

#133 Emp can now use the site
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: enhancement, refactoring

#138 Task#208
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/navbar.jsp
Labels: refactoring

#117 Mockito MySQL testing.
  FogCarport/pom.xml
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/DBCPDataSource.java
  FogCarport/src/main/java/data/databaseAccessObjects/DBConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/DataSourceMysql.java
  FogCarport/src/main/java/data/databaseAccessObjects/DatabaseConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/PartslistLogic.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/test/java/data/databaseAccessObjects/mappers/MaterialMapperTest.java
  FogCarport/src/test/java/data/databaseAccessObjects/mappers/OrderMapperTest.java
  FogCarport/src/test/java/data/databaseAccessObjects/mappers/UserMapperTest.java
  extraFiles/Database docs/viewMaterials.sql
Labels: bug, refactoring

#139 HikariCP DataSource
  FogCarport/pom.xml
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/DBConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/DataSourceMysql.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DBCPDataSource.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DBConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DataSourceMysql.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/HikariDS.java
Labels: refactoring

#142 Two bug fixes
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/webapp/homepage.jsp
Labels: bug

#143 Issue#136 back buttons fixed
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: bug

#144 Improvements to viewSVG
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: bug, enhancement

#147 Task#163: SVG for FlatRoofCalc
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingFlatRoof.java
Labels: enhancement

#146 Attempted fix for "too many connections" error.
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
Labels: bug

#149 Combined all SVG
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement

#151 Shows suggested price for customer and emp and emp can calculate on new price
  FogCarport/src/main/java/logic/Calculations/PriceCalculator.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/PartslistLogic.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: enhancement

#154 Fix for Issue#141
  FogCarport/src/main/webapp/navbar.jsp
Labels: bug

#155 Translated throwable exception messages to danish because user will see them.
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
Labels: bug

#160 Shed dropdowns and roof dropdowns fixed
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/webapp/index.jsp
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/makeCarport.jsp
  extraFiles/Database docs/insertion(DML).sql
Labels: bug, enhancement

#164 Issue#158 Improvements to viewSVG
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/viewOrder.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement

#166 Customers can now only view their own orders
  FogCarport/src/main/java/presentation/viewOrder.java
Labels: bug

#169 Design changes
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/webapp/allOrders.jsp
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/index.jsp
  FogCarport/src/main/webapp/login.jsp
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/resources/favicon.png
  FogCarport/src/main/webapp/resources/favicon2.png
  FogCarport/src/main/webapp/viewOrder.jsp
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement, suggestion

#172 Table striped
  FogCarport/src/main/webapp/partslist.jsp
Labels: refactoring, small issue

#174 First edt of raisedroof design changes
  FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
Labels: refactoring

#173 Deleted carport form.
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/UnknownCommand.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/webapp/createUser.jsp
  FogCarport/src/main/webapp/errorMessage.jsp
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/makeCarport.jsp
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/orderSuccess.jsp
  extraFiles/Diagrams/ER-Diagram.JPG
Labels: refactoring

#175 Reduced amount of connections and their duration significantly.
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/HikariDS.java
  FogCarport/src/main/java/presentation/orderCarport.java
  extraFiles/Database docs/create(DDL).sql
Labels: ! important, bug

#186 Task#158 - Sticky table header
  FogCarport/src/main/webapp/css/global.css
Labels: enhancement

#185 Task#236 - Upgrade FlatRoofCalc
  FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
  FogCarport/src/test/java/logic/Calculations/RoofFlatCalcTest.java
Labels: enhancement, refactoring

#178 task#257: add greetings message to navbar
  FogCarport/src/main/java/data/models/EmployeeModel.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/navbar.jsp
Labels: enhancement

#177 User Story #19 - Price
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/DataFacadeImpl.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/models/OrderModel.java
  FogCarport/src/main/java/logic/Calculations/PriceCalculator.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/payOrder.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/viewOrder.jsp
  extraFiles/Database docs/create(DDL).sql
Labels: enhancement

#176 JS validation for the frontpage
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: enhancement

#189 Issue#182
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/partslist.jsp
Labels: enhancement, small issue

#192 Improved JS validation for homepage.jsp
  FogCarport/src/main/webapp/javascript/global.js
Labels: bug, enhancement

#190 Quickfix for issue#183
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: small issue

#195 Improved JS and fixed Issue#187
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/javascript/global.js
Labels: bug

#194 Issue#167 - Price formatting
  FogCarport/src/main/webapp/css/global.css
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: enhancement, refactoring

#196 Fixes on connection.
  FogCarport/src/main/java/data/databaseAccessObjects/DatabaseConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/HikariDS.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
Labels: bug, refactoring

#197 Issues #162 & #181
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/presentation/FrontController.java
  extraFiles/Database docs/create(DDL).sql
Labels: enhancement, refactoring

#198 Center button text and translation
  FogCarport/src/main/webapp/viewSVG.jsp
Labels: refactoring

#200 JavaDoc, comments and some refactoring
  FogCarport/src/main/java/data/DataFacade.java
  FogCarport/src/main/java/data/databaseAccessObjects/DatabaseConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DBCPDataSource.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DBConnector.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/DataSourceMysql.java
  FogCarport/src/main/java/data/databaseAccessObjects/dataSources/HikariDS.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
  FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
  FogCarport/src/main/java/data/exceptions/AlgorithmException.java
  FogCarport/src/main/java/data/exceptions/DataException.java
  FogCarport/src/main/java/data/exceptions/UserException.java
  FogCarport/src/main/java/data/models/CustomerModel.java
  FogCarport/src/main/java/data/models/EmployeeModel.java
  FogCarport/src/main/java/data/models/MaterialModel.java
  FogCarport/src/main/java/data/models/OrderModel.java
  FogCarport/src/main/java/data/models/PartslistModel.java
  FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
  FogCarport/src/main/java/logic/Calculations/ShedLogic.java
  FogCarport/src/main/java/logic/LogicFacade.java
  FogCarport/src/main/java/logic/LogicFacadeImpl.java
  FogCarport/src/main/java/logic/PartslistLogic.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingFlatRoof.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
  FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
  FogCarport/src/main/java/presentation/Command.java
  FogCarport/src/main/java/presentation/FrontController.java
  FogCarport/src/main/java/presentation/LogOut.java
  FogCarport/src/main/java/presentation/Validation.java
  FogCarport/src/main/java/presentation/link.java
  FogCarport/src/main/java/presentation/login.java
  FogCarport/src/main/java/presentation/makeCarportForm.java
  FogCarport/src/main/java/presentation/makeCarportSimple.java
  FogCarport/src/main/java/presentation/orderCarport.java
  FogCarport/src/main/java/presentation/viewAllOrders.java
  FogCarport/src/main/java/presentation/viewOrder.java
  FogCarport/src/main/java/presentation/viewPartslist.java
  FogCarport/src/main/java/presentation/viewSVG.java
  FogCarport/src/main/webapp/allOrders.jsp
  FogCarport/src/main/webapp/homepage.jsp
  FogCarport/src/main/webapp/javascript/global.js
  FogCarport/src/main/webapp/navbar.jsp
  FogCarport/src/main/webapp/partslist.jsp
  FogCarport/src/main/webapp/viewOrder.jsp
Labels: refactoring

#205 dml update after order change
  extraFiles/Database docs/insertion(DML).sql
Labels: enhancement
